---
title: "RWorksheet_Sadural#4b"
output: pdf_document
date: "2023-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#1. Using the for loop, create an R script that will display a 5x5 matrix as shown in Figure 1. It must contain vectorA = [1,2,3,4,5] and a 5 x 5 zero matrix.

vectorA = c(1,2,3,4,5)
matrixA <-matrix (0, nrow = 5, ncol =5)

for (i in 1:5){
  for (j in 1:5){
      matrixA[i,j] <- abs(i-j)+ vectorA[j]
  }
}

print(matrixA)

#2.
vectorA <- 1:5
matrixA <- matrix(0, nrow=5, ncol=5)

for (i in 1:nrow(matrixA)) {
  for (j in 1:ncol(matrixA)) {
    matrixA[i,j] <- abs(vectorA[i]-vectorA[j])
    cat(matrixA[i,j], "\t")
  }
  cat("\n")
}

for(k in 1:5) {
  cat("*")
}

#3.
n <- as.numeric(readline(prompt = "Enter a number to start the Fibonacci sequence: "))

a <- 0
b <- 1
c <- a + b

repeat {
  if (c > 500) { 
    break
  }
  if (a == 0 & b == 1) {
    cat(b, " ")
  }
  cat(c, " ")
  a <- b
  b <- c
  c <- a + b
}

#4a.
ShoesData <- read.csv("Shoe sizes")

#4b.
maleSub <- subset(ShoesData, Gender == "M")
femSub <- subset(ShoesData, Gender == "F")

cat("The number of observation in male subset:", nrow(maleSub),"\n")
cat("The number of observation in female subset:", nrow(femSub),"\n")

#4c.
GenderMF <- table(ShoesData$Gender)

barplot(GenderMF,
        main = "Number of Male and Female in Household Data",
        xlab = "Gender",
        ylab = "Count" ,
        col = c("red", "green"),
        legend.text = c("Female", "Male"))







#5.
Incomemonth <- c("60", "10", "5", "25")

pie(Incomemonth)

pie("Delacruz_Income",
    main = "Monthly Income of Delacruz Family",
    col = rainbow(length(Incomemonth)),
    labels = c("Food", "Electricity", "Savings", "Miscellaneous"))

Incomemonth <-c("60","10","5", "25")




#6.




#7.













```

























```